const langContent = {
    "en": {
        "title": "RND",
        "dashboard": "Dashboard",
        "home": "Home",
        "link": "Link",
        "operation": "Operation",
        "fund-transfer": "Fund Transfer",
        "bill-pay": "Bill Pay",
        "balance-inquiry": "Balance Inquiry",
        "cash-operator": "Cash Operator",
        "customer-details": "Customer Details",
        "customer": "Customer",
        "search": "Search",
        "rights": "© All Rights Reserved",
        "welcome": "Welcome to our services.",
        "fund-transfer-title": "Fund Transfer",
        "balance-inquiry-title": "Balance Inquiry",
        "cash-operator-title": "Cash Operator",
        "customer-details-title": "Customer Details",
        "customer-title": "Customer"
    },
    "bn": {
        "title": "আরএনডি",
        "dashboard": "ড্যাশবোর্ড",
        "home": "হোম",
        "link": "লিংক",
        "operation": "অপারেশন",
        "fund-transfer": "ফান্ড ট্রান্সফার",
        "bill-pay": "বিল পে",
        "balance-inquiry": "ব্যালেন্স অনুসন্ধান",
        "cash-operator": "ক্যাশ অপারেটর",
        "customer-details": "গ্রাহকের বিবরণ",
        "customer": "গ্রাহক",
        "search": "অনুসন্ধান",
        "rights": "© সর্বস্বত্ব সংরক্ষিত",
        "welcome": "আমাদের সেবাতে স্বাগতম।",
        "fund-transfer-title": "ফান্ড ট্রান্সফার",
        "balance-inquiry-title": "ব্যালেন্স অনুসন্ধান",
        "cash-operator-title": "ক্যাশ অপারেটর",
        "customer-details-title": "গ্রাহকের বিবরণ",
        "customer-title": "গ্রাহক"
    },    // Add more language content here
};